import { AgentProfileSchema, type AgentProfile } from "../domain/schemas.js";

export const ORGANIZATION_ID = "10000000-0000-4000-8000-000000000001";
export const PROJECT_ID = "20000000-0000-4000-8000-000000000001";
export const OWNER_USER_ID = "30000000-0000-4000-8000-000000000001";

const sharedScope = {
  repository: "followville_repo",
  allowedPathPrefixes: ["company-os"],
  deniedPathPrefixes: [
    "world_state.json",
    "town.glb",
    "town_chunks",
    "neighborhood.blend",
  ],
  environments: ["local", "preview"] as const,
};

function profile(
  value: Omit<AgentProfile, "organizationId" | "repositoryScopes">,
): AgentProfile {
  return AgentProfileSchema.parse({
    ...value,
    organizationId: ORGANIZATION_ID,
    repositoryScopes: [sharedScope],
  });
}

export const SEED_AGENTS = {
  ceo: profile({
    id: "40000000-0000-4000-8000-000000000006",
    slug: "chief-executive",
    name: "Chief Executive",
    role: "Interpretation and prioritization",
    description:
      "Turns owner intent into initiatives, sets priority, and escalates anything that is an owner's call.",
    responsibilities: [
      "Interpret goals from Cade and Zach",
      "Decompose intent into bounded initiatives",
      "Set relative priority across open work",
      "Escalate decisions the owners must make",
      "Never widen what any agent is permitted to do",
    ],
    capabilities: ["repository_read", "memory_write", "message_send"],
    prohibitedCapabilities: [
      "repository_write",
      "git_commit",
      "production_merge",
      "production_deploy",
      "production_database_write",
      "canonical_world_growth",
      "public_communication",
      "social_publish",
      "payment_charge",
      "price_change",
      "destructive_delete",
    ],
    preferredModelClass: "standard",
    fallbackModelClass: "economy",
    maxTaskCostUsdMicros: 0,
    maxDailyCostUsdMicros: 0,
    maxRunDurationSeconds: 600,
    maxRetries: 1,
    maxConcurrentRuns: 1,
    requiresHumanApprovalFor: [],
    escalationRules: [
      "Escalate product direction, branding, monetization, and spending.",
      "Escalate anything irreversible or public.",
      "Never overrule an owner.",
    ],
    promptVersion: "chief-executive-v1",
    active: true,
  }),
  manager: profile({
    id: "40000000-0000-4000-8000-000000000001",
    slug: "company-manager",
    name: "Company Manager",
    role: "Planning and coordination",
    description: "Converts owner goals into bounded tasks and approval packets.",
    responsibilities: [
      "Decompose goals",
      "Assign independent workers and reviewers",
      "Escalate decisions to humans",
    ],
    capabilities: ["repository_read", "memory_write", "message_send"],
    prohibitedCapabilities: [
      "production_merge",
      "production_deploy",
      "production_database_write",
      "canonical_world_growth",
      "social_publish",
      "payment_charge",
      "price_change",
      "destructive_delete",
    ],
    preferredModelClass: "standard",
    fallbackModelClass: "economy",
    maxTaskCostUsdMicros: 0,
    maxDailyCostUsdMicros: 0,
    maxRunDurationSeconds: 900,
    maxRetries: 2,
    maxConcurrentRuns: 2,
    requiresHumanApprovalFor: [],
    escalationRules: [
      "Escalate ambiguous product decisions.",
      "Escalate every production or public action.",
    ],
    promptVersion: "company-manager-v1",
    active: true,
  }),
  engineer: profile({
    id: "40000000-0000-4000-8000-000000000002",
    slug: "full-stack-engineer",
    name: "Full-Stack Engineer",
    role: "Implementation",
    description: "Implements approved tasks in an isolated review branch.",
    responsibilities: ["Edit scoped files", "Run tests", "Prepare evidence"],
    capabilities: [
      "repository_read",
      "repository_write",
      "git_branch_create",
      // Held outright: the runtime records finished work on the task's own
      // review branch so an owner has something to inspect. It cannot leave
      // the machine.
      "git_checkpoint",
      // Still approval-gated below: the agent deciding to commit for itself
      // is a different act, on the path toward publication.
      "git_commit",
      // These can run only after the owner accepts the exact checkpoint. They
      // publish a review branch and draft PR; neither capability can merge.
      "git_push_review_branch",
      "pull_request_create",
      "test_execute",
      "browser_preview",
      "blender_preview",
      "memory_write",
      "message_send",
    ],
    prohibitedCapabilities: [
      "production_merge",
      "production_deploy",
      "production_database_write",
      "canonical_world_growth",
      "social_publish",
      "payment_charge",
      "price_change",
      "destructive_delete",
    ],
    preferredModelClass: "standard",
    fallbackModelClass: "economy",
    maxTaskCostUsdMicros: 0,
    maxDailyCostUsdMicros: 0,
    maxRunDurationSeconds: 1800,
    maxRetries: 2,
    maxConcurrentRuns: 1,
    requiresHumanApprovalFor: [
      "git_commit",
      "git_push_review_branch",
      "pull_request_create",
    ],
    escalationRules: ["Stop after repeated test failures.", "Never expand file scope silently."],
    promptVersion: "full-stack-engineer-v1",
    active: true,
  }),
  reviewer: profile({
    id: "40000000-0000-4000-8000-000000000003",
    slug: "qa-reviewer",
    name: "QA Reviewer",
    role: "Independent review",
    description: "Reviews evidence and acceptance criteria without implementing.",
    responsibilities: ["Review diffs", "Verify tests", "Report unresolved risk"],
    capabilities: ["repository_read", "test_execute", "message_send"],
    prohibitedCapabilities: [
      "repository_write",
      "git_commit",
      "production_merge",
      "production_deploy",
      "production_database_write",
      "canonical_world_growth",
      "social_publish",
      "payment_charge",
      "price_change",
      "destructive_delete",
    ],
    preferredModelClass: "independent_review",
    fallbackModelClass: "standard",
    maxTaskCostUsdMicros: 0,
    maxDailyCostUsdMicros: 0,
    maxRunDurationSeconds: 900,
    maxRetries: 1,
    maxConcurrentRuns: 2,
    requiresHumanApprovalFor: [],
    escalationRules: ["Reject missing evidence.", "Escalate critical findings."],
    promptVersion: "qa-reviewer-v1",
    active: true,
  }),
  costAuditor: profile({
    id: "40000000-0000-4000-8000-000000000004",
    slug: "cost-auditor",
    name: "Cost Auditor",
    role: "Budget oversight",
    description: "Checks estimates, reservations, actual costs, and anomalies.",
    responsibilities: ["Review usage ledger", "Enforce hard limits", "Flag anomalies"],
    capabilities: ["repository_read", "message_send"],
    prohibitedCapabilities: [
      "repository_write",
      "model_invoke",
      "payment_charge",
      "production_merge",
      "production_deploy",
      "production_database_write",
      "canonical_world_growth",
      "destructive_delete",
    ],
    preferredModelClass: "deterministic",
    fallbackModelClass: "deterministic",
    maxTaskCostUsdMicros: 0,
    maxDailyCostUsdMicros: 0,
    maxRunDurationSeconds: 300,
    maxRetries: 0,
    maxConcurrentRuns: 4,
    requiresHumanApprovalFor: [],
    escalationRules: ["Block any unpriced or over-budget invocation."],
    promptVersion: "cost-auditor-v1",
    active: true,
  }),
  reporter: profile({
    id: "40000000-0000-4000-8000-000000000005",
    slug: "executive-reporter",
    name: "Executive Reporter",
    role: "Human-readable reporting",
    description: "Summarizes verified work, uncertainty, decisions, and costs.",
    responsibilities: ["Prepare concise status reports", "Link evidence", "Label uncertainty"],
    capabilities: ["repository_read", "message_send"],
    prohibitedCapabilities: [
      "repository_write",
      "public_communication",
      "social_publish",
      "production_merge",
      "production_deploy",
      "production_database_write",
      "canonical_world_growth",
      "payment_charge",
      "destructive_delete",
    ],
    preferredModelClass: "economy",
    fallbackModelClass: "deterministic",
    maxTaskCostUsdMicros: 0,
    maxDailyCostUsdMicros: 0,
    maxRunDurationSeconds: 300,
    maxRetries: 1,
    maxConcurrentRuns: 2,
    requiresHumanApprovalFor: [],
    escalationRules: ["Do not present unverified claims as completed work."],
    promptVersion: "executive-reporter-v1",
    active: true,
  }),
} as const;
